### ISSUE TITLE
Unable to run the 3Dcartesian_sinkingslab in cookbook

### ISSUE THREAD

**Issue by Peigen-L** [mfaccenda/ECOMAN#2]
Hello,

I am using **ECOMAN2.0-geodynamics** to generate synthetic SKS-splitting parameters from a 3D model run by **Underworld2**.

I successfully installed **ECOMAN2.0-geodynamics** on our local cluster. However, when running the **3Dcartesian_sinkingslab** case, I encountered the following error message:

![ErrorMsg](https://github.com/user-attachments/assets/f0acea66-e427-4e93-bfce-6b601f61ff7d)

The error seems to indicate that **HDF5** failed to load the file `fossilfabric.h5` located in `../D-Rex_S/`, causing the process to fail. After searching through both our local directory and the GitHub repository, I could not locate any file named `fossilfabric.h5` in `../D-Rex_S/`.

Could you please advise on how to resolve this issue?

Thank you very much for your help!

Best regards,  
Peigen

**Comment by ecoman-geos** [comment]
Hi Peigen,

I'm glad you have been able to successfully install the package in your cluster.

about the issue you have encountered, the thing is that you should first generate the fossil fabric by running D-REX_S which stores it in fossilfabric.h5. Subsequently, you can run D-REX_M. 
Alternatively set the flag fossilfabric to 0 in drexm_input.dat.

Best regards,
Manuele

**Comment by Peigen-L** [comment]
Hi Professor,

It seems working right now. It generated tensor files named as Cijkl as D-REX did.

![图像](https://github.com/user-attachments/assets/80b25d37-b470-405f-bee2-9d639d3fa665)
let me explore it a little bit.

I really appreciate ECOMAN2.0—it’s a fantastic enhancement for geodynamics modeling software like Underworld2 and I3VIS. Constraining model mantle convection with natural observations, such as SKS splitting, is always a challenge, and ECOMAN2.0 makes this process much more accessible.

Kind Regards
Peigen

**Comment by ecoman-geos** [comment]
Dear Peigen,

thanks for your support.
Enjoy ECOMAN!

Best regards,
Manuele

**Comment by Peigen-L** [comment]
Hi team,

I encountered an error when running SKS splitting calculations on the 3D Cartesian sinking slab case in ECOMAN2.0.

**Setup:**
1. I generated the `Cijkl` file using `D_REX_M` and saved it to the path `…/3Dcartesian_sinkingslab/Cijkl0020.h5`.
2. I created a new PBS file, adapting parameters from `pbs_sks`.
**PBS:**
```
#! /bin/sh
#SBATCH -J LPG_sks
#SBATCH --ntasks=28
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --mem=64000
#SBATCH --cpus-per-task=1
#SBATCH --distribution=cyclic
source /opt/rh/devtoolset-9/enable
source /opt/intel/oneapi/setvars.sh intel64 --force
export OMP_NUM_THREADS=1
cd /home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-seismology.SKS-SPLIT/
cijkl_dir= /home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/Cijkl0020.h5
timestep=0020
mode=0
split_dir=splitting
avg=0
verbose=0
save_bascan=1
idisp=15
varpar=1
density=3.353
incidence=5
bottom=400
lith_bot=100
execute=1
echo 1
./stack_calc $cijkl_dir $timestep $mode
wait
echo 2
srun -N 1 -n 28 --mem=64000 ./split_calc $cijkl_dir $timestep $mode $split_dir $avg $verbose $save_bascan $idisp $varpar $density $incidence $bottom $lith_bot $execute
echo 3
```

**Error Message:**
Upon submission, it appears `Cijkl0020.h5` can’t load correctly:
```
:: initializing oneAPI environment ...
   slurm_script: BASH_VERSION = 4.2.46(2)-release
   args: Using "$@" for setvars.sh arguments: intel64 --force
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: inspector -- latest
:: ipp -- latest
:: ippcp -- latest
:: itac -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/Cijkl0020.h5: line 1: ‰HDF
: command not found
/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/Cijkl0020.h5: line 2: $'\032': command not found
/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/Cijkl0020.h5: line 3: syntax error near unexpected token `('
/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/Cijkl0020.h5: line 3: `ÿÿÿÿÿÿÿÿØnëÿÿÿÿÿÿÿÿ`ˆ¨ (TREEÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿHEAPX ÈNodesParticles8ˆ¨XCoordinateSystem P	Periodic PTime ?@44ÿ`¡ö†BvXPŸFuÊBPhTREEÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÈHEAPX °gxgygz8SNODHp0XxpHnxyz %%%%% ?@44ÿÈ	([ÿ2gxÇqÇq ë@ÇqÇq û@UUUUUXAÇqÇq AÇqGôAUUUUUXAŽã8Žc¼AÇqÇq A€„AÇqGô A8Žã8N¦"ATUUUUX$ApÇq\'
1
./stack_calc: Geodynamic model directory: 0020
./stack_calc: Seismic stations directory: 0020/seismic_stations/
rm: cannot remove â€˜0020/seismic_stations//*â€™: No such file or directory
./savstack: error while loading shared libraries: libsz.so.2: cannot open shared object file: No such file or directory
mv: cannot stat â€˜seismic_station_*.savâ€™: No such file or directory
mv: cannot stat â€˜Surface_coordinates.datâ€™: No such file or directory
```
Additional errors suggest issues with directories (`cpu` not found), missing libraries (`libsz.so.2`), and a syntax error with `gawk`.

Could you advise on resolving these HDF and file path errors?

Kind Regard,
Peigen

**Comment by mfaccenda** [comment]
Dear Peigen

Please remove Cijkl0020.h5 from the path, which should only contain the
path to the directory. The file to be loaded is specified in variable
timestep.

Best
Manuele

Il giorno mar 12 nov 2024 alle 09:22 Luo Peigen ***@***.***>
ha scritto:

**Comment by Peigen-L** [comment]
Hi Professor,

Thank you for your reply.

I have tried to remove Cijkl0020.h5 from the path.
However, I still got error as: 
![image](https://github.com/user-attachments/assets/87cd5fbe-c275-488d-84b9-5dae81bbd5ae)

I can see some folders generated under the working path: `/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-seismology.SKS-SPLIT/` as shown below:
![image](https://github.com/user-attachments/assets/75f91bb0-1dc3-4ead-9159-b390951e9bd3)
However, they are almost empty. Especially for the folder 0020 where the tensor files should be alocated in.

Can you please advise on resolving this issue?

Kind regards
Peigen

**Comment by Peigen-L** [comment]
Hi Professor,

I recently adjusted the first argument in the PBS script, but encountered the following error message upon rerunning the job:

![image](https://github.com/user-attachments/assets/0d094e6c-eb55-4fff-9983-33841f485b94)

The stack_calc script attempts to move the files `seismic_station_*.sav` and `Surface_coordinates.dat` to `.../cookbooks/3Dcartesian_sinkingslab/seismic_stations/,` but it seems these datasets are missing. Could you confirm whether these files should be auto-generated by a previous step in the workflow or if they need to be provided manually?

Are the two required datasets auto-generated?

Can you please advise on this issue?

Kind regards

Peigen

**Comment by ecoman-geos** [comment]
Hi Peigen,

cijkl_dir should be the path to the directory where the Cijkl0020.h5 file is, and which I think in your case is:

cijkl_dir= /home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/out/

Basically what you want to do here is to open the D-REX_M output and post-process it for SKS splitting computations.

Let me know if it works.

Best,
Manuele

**Comment by Peigen-L** [comment]
Hi Manuele,

I’d like to first provide an overview of my approach and current progress. I have a large-scale 3D subduction model created using Underworld2, with velocity fields saved in `.h5` format, along with other datasets organized for analysis. 
My goal is to compare synthetic "SKS" bars generated from my model’s mantle velocity fields with real-world SKS measurements. In this figure, I generated the "SKS" bars by integrating the upper mantle velocity beneath points arrayed on surfaces representing seismic stations. However, I believe it would make more sense to use **ECOMAN2.0** for generating the synthetic SKS bars, as it offers a more appropriate framework for this type of analysis.

Currently, I am working with ECOMAN2.0 and attempting to run the `3Dcartesian_sinkingslab` example, which closely resembles my model setup. I executed the following command in the working directory:

```bash
mpirun -np 28 ./drexm ../cookbooks/3Dcartesian_sinkingslab/drexm_input.dat
```

The only output I received was the `Cijkl data` file, named `Cijkl0020.h5`, which was saved in the following directory:

```
/home/GeoScientists/Luo_Peigen/Softwares/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/out/
```

Next, I attempted to post-process the `Cijkl` file for SKS splitting computations, using the PBS file and `stack_input.dat` configuration provided below:

**PBS file:**
![PBS Image](https://github.com/user-attachments/assets/f1370822-34aa-4ad2-9f99-629c6bacee06)

**stack_input.dat:**
![stack_input.dat Image](https://github.com/user-attachments/assets/469f81ae-6195-42b3-8bf9-eac43cfffcf9)

Unfortunately, I encountered the same error message as shown here:

![Error Message](https://github.com/user-attachments/assets/af74d491-6ade-4b3b-bf6a-53fb8803d1d0)

At this point, I’m stuck and would greatly appreciate any assistance you can provide in resolving this issue.

Once this issue is resolved, I plan to use `makevtpfiles.m` to generate VTP files for my model and proceed with the workflow to generate the synthetic SKS bars.

Thank you for your help!

Kind regards,  
Peigen

**Comment by mfaccenda** [comment]
Dear Peigen
And have you run bash_compile to compile savstack and the other codes
required for sks splitting ?

Best
Manuele

Il giorno mer 13 nov 2024 alle 08:12 Luo Peigen ***@***.***>
ha scritto:

**Comment by Peigen-L** [comment]
Yes, I’ve already run ./savstack 0 0020 in the terminal, and it worked as expected. The output, including seismic_station_*.sav and Surface_coordinates.dat, was generated quickly in the working directory.

So, the savstack tool is functioning properly. The issue must lie with the PBS script I wrote.

Let me double-check the PBS script. Alternatively, I’m considering running the process without MPI since the calculation isn’t computationally intensive.

Kind regards

Peigen

**Comment by ecoman-geos** [comment]
it looks like than when you launch the pbs script some libraries (libsz) required by hdf5 are not loaded, so this might be the problem.

**Comment by Peigen-L** [comment]
Yes, I noticed this as well.
Maybe this is the problem.
I will double check our local cluster's HDF5 configuration as well. It seems the HDF didn't load correctly when using PBS.
This may also causing problem when using Underworld in the future.
I’ll provide an update on the progress once I have more information.

Kind regards
Peigen

**Comment by Peigen-L** [comment]
**Subject:** Assistance Needed with MPI Implementation and sav2cijkl Process  

Dear Professor,  

I hope this email finds you well.  

I have updated my PBS script, and it now appears to run with Open MPI. I am using Open MPI 1.10.7 and have implemented the following modifications to obtain the number of CPUs and their ranks:  

```bash  
multi_cpu=$OMPI_COMM_WORLD_SIZE  # Get number of CPUs  
proc_id=$OMPI_COMM_WORLD_RANK   # Get CPU rank  

echo $OMPI_COMM_WORLD_SIZE  
echo $OMPI_COMM_WORLD_RANK  
```  

I executed the following command:  

```bash  
mpirun -np 8 ./split_calc /home/GeoScientists/Luo_Peigen/Software/D_REX/ECOMAN2.0-geodynamics/cookbooks/3Dcartesian_sinkingslab/out 0020 0 splitting 0 0 1 15 1 3.353 5 400 100 1  
```  

The working directory structure is as expected:  

- Each CPU has its own folder (e.g., CPU0, CPU1).  
- Within each folder (e.g., CPU0), the setup files and outputs are generated correctly.  

However, the process seems to stall at the `sav2cijkl` stage, where the generated `depth_15.cijkl` file is empty.  

The following error message is returned:  
![image](https://github.com/user-attachments/assets/bec6fd6d-bafb-43c1-a830-e71844028702)

I have verified the inputs and configurations but cannot identify the root cause of this issue. Any advice or guidance on resolving this would be greatly appreciated.  

Kind regards,  
Peigen

**Comment by Peigen-L** [comment]
It seems started working right now:
I have changed:
```
multi_cpu=$MPI_LOCALNRANKS # get number of CPUs
echo $multi_cpu
proc_id=$MPI_LOCALRANKID 		# get CPU rank
echo $proc_id
```

Kind regard

Peigen

**Comment by ecoman-geos** [comment]
Dear Peigen,

glad to hear that now the code is working. 
Thanks for sharing the modifications, I will consider them for future releases of the software.

Best wishes,
Manuele

**Comment by Peigen-L** [comment]
Dear professor,

The visualized results look stunning and highly informative!

![image](https://github.com/user-attachments/assets/50735df9-cb2b-4abb-ae91-158fab12a18e)
 The output from ECOMAN2.0 is impressive, and I am genuinely thrilled by the clarity and detail it provides. I plan to proceed with analyzing my own model's VTP files and will share updates as I make progress.

Thank you for this incredible tool—ECOMAN2.0 is truly remarkable!

kind regards
Peigen
